export default {
  mainFrame: 10,
  bodyHPadding: 24,
  smallCornerRadius: 5,
  bigCornerRadius: 40,
  mediumCornerRadius: 20,
  textHPadding: 5,
  buttonBorderRadius: 20,
  buttonHPadding: 10,
  buttonVPadding: 5,
  buttonHeight: 50,
  buttonWidth: 140,
  elevation: 5,
  separator: 8,
  iconSize: 50,
  airbnbRed: "#FF5A60",
};
