export default {
  maxTextLength: 255,
  maxRating: 5,
  minRating: 0,
  maxCount: 99,
  ERR_EMAIL_IN_USE: "Ya existe una cuenta con esta direccion de email",
  ERR_EMAIL_INVALID: "El email es invalido",
  ERR_PASS_INVALID: "Contraseña incorrecta",
  ERR_EMPTY_FIELD: "Uno o mas campos no han sido completados",
  ERR_EMPTY_REVIEW: "No puede publicar una reseña vacia",
  ERR_RATING_ZERO: "Puntaje no puede ser 0",
  FORGOT_PASSWORD_MESSAGE: "¿Olvidaste tu contraseña?",
  CACHE_USER_KEY: "loggedInUser",
  CACHE_ROOM_KEY: "currentRoom",
  BOOKING_STATUS_PENDING: 1,
  BOOKING_STATUS_ACCEPTED: 2,
  MAX_DESCRIPTION_LENGTH: 256,
};
